### ISSUE TITLE
프로세스와 스레드의 차이

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#1]
📍 스터디 날짜 : 2022년 11월 23일

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/f5453df0a6914b96849c90ab9bc864a4

**Comment by ungchun** [comment]
https://ungchun.notion.site/3511333ec2474b97b24073ae4639b532

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%201/%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EC%99%80%20%EC%8A%A4%EB%A0%88%EB%93%9C%EC%9D%98%20%EC%B0%A8%EC%9D%B4.md

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/6aeabe937cac4113a077d6db2a6593f4
