### ISSUE TITLE
IPC(Inter Process Communication)

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#10]
📍 스터디 날짜 : 2022년 12월 7일

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%203/IPC(Inter_Process_Communication).md

**Comment by ungchun** [comment]
https://www.notion.so/ungchun/IPC-Inter-Process-Communication-b160799a77cf4feca4f57ba083b07046

**Comment by dudtjs1021ej** [comment]
https://lucky-count-b4e.notion.site/IPC-Inter-Process-Communication-f065f668567f468e9fc610f0af93c94f

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/IPC-Inter-Process-Communication-9c091bb0ad0e49469064e7e41c2e1af4

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/IPC-Inter-Process-Communication-f5f58e0c832f45758c69acf7eaf890f6
