### ISSUE TITLE
페이징/세그멘테이션

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#12]
📍 스터디 날짜 : 2022년 12월 7일

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%203/%ED%8E%98%EC%9D%B4%EC%A7%95%EA%B3%BC_%EC%84%B8%EA%B7%B8%EB%A9%98%ED%85%8C%EC%9D%B4%EC%85%98.md

**Comment by ungchun** [comment]
https://www.notion.so/ungchun/06f4d159cc774d928cf746c732c93df2

**Comment by dudtjs1021ej** [comment]
https://lucky-count-b4e.notion.site/51286f5ba49f48b18d18ed4418f2ca89

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/5213f2ba4e114db9af7bb962af390c52

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/bf72fdf1aa3145db8172f7619e3a511e
