### ISSUE TITLE
프로세스 주소 공간

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#2]
📍 스터디 날짜 : 2022년 11월 23일

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/fb74473d2d684bf29d47fea9a7aa8177

**Comment by ungchun** [comment]
https://ungchun.notion.site/419d4db78e664b3ab65520b293e1ef5c

**Comment by dudtjs1021ej** [comment]
https://lucky-count-b4e.notion.site/901453aff20b49dda0ad26491e02b1e1

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%201/%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4_%EC%A3%BC%EC%86%8C_%EA%B3%B5%EA%B0%84.md

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/16a78c4732c247b3ae4af6a374032682
