### ISSUE TITLE
인터럽트, 시스템 콜

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#5]
📍 스터디 날짜 : 2022년 11월 30일

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%202/%EC%9D%B8%ED%84%B0%EB%9F%BD%ED%8A%B8%2C_%EC%8B%9C%EC%8A%A4%ED%85%9C%20%EC%BD%9C.md

**Comment by ungchun** [comment]
https://ungchun.notion.site/e69b51c90f3c4cea992ed728dc0cc429

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/7606b7d6c90a480b8f94b7c38c7a604b

**Comment by dudtjs1021ej** [comment]
https://www.notion.so/04ce4eb87c4d41e88a7b5a5e3174aea2

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/efdddea7847640f28bbef16739e1d13a
