### ISSUE TITLE
CPU 스케줄러

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#6]
📍 스터디 날짜 : 2022년 11월 30일

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%202/CPU_%EC%8A%A4%EC%BC%80%EC%A4%84%EB%9F%AC.md

**Comment by ungchun** [comment]
https://ungchun.notion.site/e69b51c90f3c4cea992ed728dc0cc429

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/CPU-f8340fd37f6340aa81780c3a53a18aa8

**Comment by dudtjs1021ej** [comment]
https://lucky-count-b4e.notion.site/CPU-1327cf82f8ea4e95a5308b7a8fd36874

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/CPU-91cb5572c9324f01919ae771613368ca
