### ISSUE TITLE
동기와 비동기의 차이

### ISSUE THREAD

**Issue by anyukyung** [DontSC-LetsCS/DontSC-LetsCS#7]
📍 스터디 날짜 : 2022년 11월 30일

**Comment by leeari95** [comment]
https://github.com/DontSC-LetsCS/DontSC-LetsCS/blob/main/Ari/Week%202/%EB%8F%99%EA%B8%B0%EC%99%80_%EB%B9%84%EB%8F%99%EA%B8%B0%EC%9D%98_%EC%B0%A8%EC%9D%B4.md

**Comment by ungchun** [comment]
https://ungchun.notion.site/e60df6aee819486c8b1e05b628850f02

**Comment by anyukyung** [comment]
https://plucky-boot-fc9.notion.site/fa1e5568fe794f20b40d0ba9eec63f9b

**Comment by dudtjs1021ej** [comment]
https://lucky-count-b4e.notion.site/565388de4440440f81e10d7e7ffe1fdd

**Comment by seonyoung42** [comment]
https://grizzly-swift-83d.notion.site/f46a8c74bb5a465b9f69eadcb291391c
